; Copyright (c) 2025 Gerald Reno, Jr.
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
; http://www.apache.org/licenses/LICENSE-2.0

.segment "CARTBANK1"
    .export _cvcvcDict2
_cvcvcDict2:
    .byte "COVET"
    .byte "DAVIT"
    .byte "DEBAR"
    .byte "DEBIT"
    .byte "DECAF"
    .byte "DECAL"
    .byte "DECOR"
    .byte "DEFER"
    .byte "DEMON"
    .byte "DENIM"
    .byte "DEPOT"
    .byte "DETER"
    .byte "DEVIL"
    .byte "DIGIT"
    .byte "DIMER"
    .byte "DINER"
    .byte "DIRER"
    .byte "DIVAN"
    .byte "DIVER"
    .byte "DIVOT"
    .byte "DONOR"
    .byte "FACET"
    .byte "FAGOT"
    .byte "FAKER"
    .byte "FAKIR"
    .byte "FATAL"
    .byte "FAVOR"
    .byte "FECAL"
    .byte "FELON"
    .byte "FERAL"
    .byte "FETAL"
    .byte "FEVER"
    .byte "FIBER"
    .byte "FILET"
    .byte "FINAL"
    .byte "FINER"
    .byte "FIVER"
    .byte "FOCAL"
    .byte "GAMER"
    .byte "GAMIN"
    .byte "GAVEL"
    .byte "GIVEN"
    .byte "GOFER"
    .byte "GONER"
    .byte "HABIT"
    .byte "HALER"
    .byte "HALON"
    .byte "HAREM"
    .byte "HATER"
    .byte "HAVEN"
    .byte "HAVOC"
    .byte "HELOT"
    .byte "HERON"
    .byte "HIKER"
    .byte "HOGAN"
    .byte "HOMER"
    .byte "HONOR"
    .byte "HOTEL"
    .byte "HOVEL"
    .byte "HOVER"
    .byte "KABOB"
    .byte "KAPOK"
    .byte "KARAT"
    .byte "KEBAB"
    .byte "KEBOB"
    .byte "KOPEK"
    .byte "LABEL"
