; Copyright (c) 2025 Gerald Reno, Jr.
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
; http://www.apache.org/licenses/LICENSE-2.0

.RODATA
    .export _cvcvcDict
_cvcvcDict:
    .byte "BABEL", $1
    .byte "BACON", $1
    .byte "BAGEL", $1
    .byte "BAKER", $1
    .byte "BANAL", $1
    .byte "BARER", $1
    .byte "BARON", $1
    .byte "BASAL", $1
    .byte "BASER", $1
    .byte "BASIC", $1
    .byte "BASIL", $1
    .byte "BASIN", $1
    .byte "BATIK", $1
    .byte "BATON", $1
    .byte "BEBOP", $1
    .byte "BEFIT", $1
    .byte "BEFOG", $1
    .byte "BEGAN", $1
    .byte "BEGAT", $1
    .byte "BEGET", $1
    .byte "BEGIN", $1
    .byte "BEGOT", $1
    .byte "BERET", $1
    .byte "BESET", $1
    .byte "BESOM", $1
    .byte "BESOT", $1
    .byte "BEVEL", $1
    .byte "BICEP", $1
    .byte "BIDET", $1
    .byte "BIGOT", $1
    .byte "BIKER", $1
    .byte "BISON", $1
    .byte "BONER", $1
    .byte "BORER", $1
    .byte "BORON", $1
    .byte "BOSOM", $1
    .byte "CABAL", $1
    .byte "CABIN", $1
    .byte "CADET", $1
    .byte "CALIF", $1
    .byte "CAMEL", $1
    .byte "CANAL", $1
    .byte "CANON", $1
    .byte "CAPER", $1
    .byte "CAPON", $1
    .byte "CARAT", $1
    .byte "CARET", $1
    .byte "CAROL", $1
    .byte "CAROM", $1
    .byte "CATER", $1
    .byte "CAVIL", $1
    .byte "CEDAR", $1
    .byte "CIDER", $1
    .byte "CIGAR", $1
    .byte "CIVET", $1
    .byte "CIVIC", $1
    .byte "CIVIL", $1
    .byte "COLIC", $1
    .byte "COLON", $1
    .byte "COLOR", $1
    .byte "COMER", $1
    .byte "COMET", $1
    .byte "COMIC", $1
    .byte "CONIC", $1
    .byte "CORAL", $1
    .byte "COVEN", $1
    .byte "COVER", $1
    .byte "COVET", $1
    .byte "DAVIT", $1
    .byte "DEBAR", $1
    .byte "DEBIT", $1
    .byte "DECAF", $1
    .byte "DECAL", $1
    .byte "DECOR", $1
    .byte "DEFER", $1
    .byte "DEMON", $1
    .byte "DENIM", $1
    .byte "DEPOT", $1
    .byte "DETER", $1
    .byte "DEVIL", $1
    .byte "DIGIT", $1
    .byte "DIMER", $1
    .byte "DINER", $1
    .byte "DIRER", $1
    .byte "DIVAN", $1
    .byte "DIVER", $1
    .byte "DIVOT", $1
    .byte "DONOR", $1
    .byte "FACET", $1
    .byte "FAGOT", $1
    .byte "FAKER", $1
    .byte "FAKIR", $1
    .byte "FATAL", $1
    .byte "FAVOR", $1
    .byte "FECAL", $1
    .byte "FELON", $1
    .byte "FERAL", $1
    .byte "FETAL", $1
    .byte "FEVER", $1
    .byte "FIBER", $1
    .byte "FILET", $1
    .byte "FINAL", $1
    .byte "FINER", $1
    .byte "FIVER", $1
    .byte "FOCAL", $1
    .byte "GAMER", $1
    .byte "GAMIN", $1
    .byte "GAVEL", $1
    .byte "GIVEN", $1
    .byte "GOFER", $1
    .byte "GONER", $1
    .byte "HABIT", $1
    .byte "HALER", $1
    .byte "HALON", $1
    .byte "HAREM", $1
    .byte "HATER", $1
    .byte "HAVEN", $1
    .byte "HAVOC", $1
    .byte "HELOT", $1
    .byte "HERON", $1
    .byte "HIKER", $1
    .byte "HOGAN", $1
    .byte "HOMER", $1
    .byte "HONOR", $1
    .byte "HOTEL", $1
    .byte "HOVEL", $1
    .byte "HOVER", $1
    .byte "KABOB", $1
    .byte "KAPOK", $1
    .byte "KARAT", $1
    .byte "KEBAB", $1
    .byte "KEBOB", $1
    .byte "KOPEK", $1
    .byte "LABEL", $1
    .byte "LABOR", $1
    .byte "LADEN", $1
    .byte "LAGER", $1
    .byte "LAMER", $1
    .byte "LAPEL", $1
    .byte "LASER", $1
    .byte "LATER", $1
    .byte "LEGAL", $1
    .byte "LEGIT", $1
    .byte "LEMON", $1
    .byte "LEPER", $1
    .byte "LEVEL", $1
    .byte "LEVER", $1
    .byte "LIBEL", $1
    .byte "LICIT", $1
    .byte "LIFER", $1
    .byte "LIKEN", $1
    .byte "LIKER", $1
    .byte "LILAC", $1
    .byte "LIMIT", $1
    .byte "LINEN", $1
    .byte "LINER", $1
    .byte "LITER", $1
    .byte "LIVEN", $1
    .byte "LIVER", $1
    .byte "LOCAL", $1
    .byte "LOGIC", $1
    .byte "LOGIN", $1
    .byte "LOGON", $1
    .byte "LONER", $1
    .byte "LOSER", $1
    .byte "LOVER", $1
    .byte "MADAM", $1
    .byte "MAGIC", $1
    .byte "MAKER", $1
    .byte "MANIC", $1
    .byte "MANOR", $1
    .byte "MASON", $1
    .byte "MAVEN", $1
    .byte "MAVIN", $1
    .byte "MEDAL", $1
    .byte "MEDIC", $1
    .byte "MELON", $1
    .byte "MERIT", $1
    .byte "METAL", $1
    .byte "METER", $1
    .byte "MILER", $1
    .byte "MIMIC", $1
    .byte "MINER", $1
    .byte "MINIM", $1
    .byte "MINOR", $1
    .byte "MISER", $1
    .byte "MITER", $1
    .byte "MODAL", $1
    .byte "MODEL", $1
    .byte "MODEM", $1
    .byte "MOLAR", $1
    .byte "MORAL", $1
    .byte "MORON", $1
    .byte "MOTEL", $1
    .byte "MOTIF", $1
    .byte "MOTOR", $1
    .byte "MOVER", $1
    .byte "NABOB", $1
    .byte "NADIR", $1
    .byte "NASAL", $1
