; Copyright (c) 2025 Gerald Reno, Jr.
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
; http://www.apache.org/licenses/LICENSE-2.0

.segment "CARTBANK0"
    .export _cvcvcDict1
_cvcvcDict1:
    .byte "BABEL"
    .byte "BACON"
    .byte "BAGEL"
    .byte "BAKER"
    .byte "BANAL"
    .byte "BARER"
    .byte "BARON"
    .byte "BASAL"
    .byte "BASER"
    .byte "BASIC"
    .byte "BASIL"
    .byte "BASIN"
    .byte "BATIK"
    .byte "BATON"
    .byte "BEBOP"
    .byte "BEFIT"
    .byte "BEFOG"
    .byte "BEGAN"
    .byte "BEGAT"
    .byte "BEGET"
    .byte "BEGIN"
    .byte "BEGOT"
    .byte "BERET"
    .byte "BESET"
    .byte "BESOM"
    .byte "BESOT"
    .byte "BEVEL"
    .byte "BICEP"
    .byte "BIDET"
    .byte "BIGOT"
    .byte "BIKER"
    .byte "BISON"
    .byte "BONER"
    .byte "BORER"
    .byte "BORON"
    .byte "BOSOM"
    .byte "CABAL"
    .byte "CABIN"
    .byte "CADET"
    .byte "CALIF"
    .byte "CAMEL"
    .byte "CANAL"
    .byte "CANON"
    .byte "CAPER"
    .byte "CAPON"
    .byte "CARAT"
    .byte "CARET"
    .byte "CAROL"
    .byte "CAROM"
    .byte "CATER"
    .byte "CAVIL"
    .byte "CEDAR"
    .byte "CIDER"
    .byte "CIGAR"
    .byte "CIVET"
    .byte "CIVIC"
    .byte "CIVIL"
    .byte "COLIC"
    .byte "COLON"
    .byte "COLOR"
    .byte "COMER"
    .byte "COMET"
    .byte "COMIC"
    .byte "CONIC"
    .byte "CORAL"
    .byte "COVEN"
    .byte "COVER"
