; Copyright (c) 2025 Gerald Reno, Jr.
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
; http://www.apache.org/licenses/LICENSE-2.0

;   Audio Driver convenience constants for notes


B8	=	3
G8	=	4
E8	=	5
D8	=	6
; C8    6.5ish? official: 4186.009   TRIPLE HIGH C

B7	=	7
A7	=	8
G7	=	9
Fs7	=	10
F7	=	11
Ds7	=	12
Cs7	=	13
C7	=	14 ; official: 2093.005   NTSC: 2130.667  PAL: 2111.233  DOUBLE HIGH C

B6	=	15
As6	=	16
A6	=	17
Gs6	=	18
G6	=	19
Fs6	=	21
F6	=	22
E6	=	23
Ds6	=	25
D6	=	26
Cs6	=	28
C6	=	29 ; official: 1046.502   NTSC: 1065.333  PAL: 1055.616  HIGH C

B5  =   31 ; this is what voice 0 always is
As5	=	33
A5	=	35
Gs5	=	37
G5	=	40
Fs5	=	42
F5	=	45
E5	=	47
Ds5	=	50
D5	=	53
Cs5	=	57
C5	=	60 ; official:  523.251Hz NTSC:  523.934  PAL:  519.155  TREBLE C

B4	=	64
As4	=	67
A4	=	71
Gs4	=	76
G4	=	81
Fs4	=	85
F4	=	91
E4	=	96
Ds4	=	102
D4	=	108
Cs4	=	114
C4	=	121 ; official:  261.626Hz NTSC:  261.967  PAL:  259.577  MIDDLE C

B3	=	128
As3	=	136
A3	=	144
Gs3	=	153
G3	=	162
Fs3	=	172
F3	=	182
E3	=	193
Ds3	=	204
D3	=	217
Cs3	=	230
C3	=	243 ; official:  130.816   NTSC:  130.983  PAL:  129.789  TENOR C

B2	=	255
; C2    N/A official:   65.408Jz                                LOW C




