; Copyright (c) 2025 Gerald Reno, Jr.
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
; http://www.apache.org/licenses/LICENSE-2.0

    .define aqordl_version "1.03a"
    .define year "2025"
    .define copyright_dict .concat("Aqordl Dictionary ",aqordl_version," Copyright (c)",year," Gerald Reno, Jr. ")


; After updating this file, also update:
;   VERSIONS.md
;   NOTICE
;   README.md (the filenames in the "Starting the game" section)

